### ISSUE TITLE
Hope live time updated

### ISSUE THREAD

**Issue by redleafnew** [igorjrd/vscode-cslpreview#11]
Great extenstion!!
Hope the CSL preview is live time updated during code editing, or updated when the code was saved.

**Comment by igorjrd** [comment]
Thanks by complimenting the extension!

I'll add it in the extension roadmap. In the initial concept of the extension I tried to implement this in a simple way, but it was leading to stuck the bibliographic processing. I already think a workaround that probably would make feasible. Anyway, some unexpected behavior would occur when the user is editing the CSL code, such as showing just syntax errors instead of the bibliographic preview.

I also ask some patience to implement this feature, as I am a sole developer of the extension

**Comment by redleafnew** [comment]
Thanks for your kind reply.

**Comment by igorjrd** [comment]
@redleafnew

I just released an update that provide the requested functionality. Please notice that it is necessary to check the option related to auto preview refresh in extension settings, otherwise the extension will keep presenting the old behavior (only refreshes when refresh command triggered).

I preferred to keep this functionality disabled as default because a dependency (the CSL validation) crashes when is called too often (even with some workaround preventing excessive calls). Anyway, in actual extension design this crashes only is occurring with some effort by user (extremely fast typing), so I think that the functionality is safe to use.

I would be grate if you send me any feedback telling if this functionality is attending your demands. Also, it would be nice if you could rate the extension in vscode marketplace.
