### ISSUE TITLE
Not generating annotated bibliography

### ISSUE THREAD

**Issue by yak-22** [igorjrd/vscode-cslpreview#2]
There are a few cls files as dictated by https://guides.zsr.wfu.edu/zotero/annotated-bib that add annotations from the Zotero `extra` or `abstract` fields. When using CLS preview for the official `chicago-annotated-bibliography.csl` I did not note any additional annotation. 
If I had to guess this issue is caused by the lack of those fields being populated.

Edit: The [example_items.json](https://github.com/igorjrd/vscode-cslpreview/blob/f625325877c0558dd05f9240b9a61fa9c36e0857/src/resources/example_items.json) indeed does not have an `extra` field. However, when exporting to CSL JSON the `extra` field gets converted into a `notes` field like in the snippet below.
 ```
"language": "en",
"note": "Testing Extra Field",
```

**Comment by igorjrd** [comment]
Hello @yak-22,

The example documents included at the extension are based in www.zotero.org/styles examples (which appear when you keep the pointer over a style link). I compared the preview results shown by the extension, by www.zotero.org/styles and by Zotero style editor and noticed that they only differ in their order.

As an option to allow users to preview `extra` or `abstract` fields, some entry can be added to the `notes` field of [example_items.json](https://github.com/igorjrd/vscode-cslpreview/blob/f625325877c0558dd05f9240b9a61fa9c36e0857/src/resources/example_items.json). Other options to provide the desired functionallity would be allowing users to select a custom JSON documents file, or integrate the extension with Zotero to get the documents using Zotero Add/Edit Citation window. I want to implement both approaches since some time ago, however, poor time availability turned it hard to develop.

I think that implement a functionallity that allow users to use a custom JSON documents file would be more interesting than simply add entries to `notes` field, as custom JSON documents would provide more freedom to users to check previews with their interest documents. Moreover, this functionallity would be quite easy to implement.

What do you think about these proposals?

**Comment by yak-22** [comment]
@igorjrd

I think that the feature to add custom CSL JSON files or a direct connection to Zotero would be useful and certainly expands the capabilities of the extension. However, I think that it is out of scope for this issue. When creating a new style the extension should provide the expected output without any additional setup on the user's end for all use cases. Because annotated bibliography is a valid use case it should provide the expected output. I understand that your extension inherited the limitations of the official CSL previewer. 
Thanks and enjoy

**Comment by igorjrd** [comment]
@yak-22,

Right now I noticed that the extension seems to ignore `notes` field entry. In fact, the preview given by the extension is different to the Zotero Style Editor preview. The CSL processor (citeproc-js) gives objects as results, so I'll check how `notes` entries are returned by citeproc-js and will adequate the code to append this return in the preview HTML code. Thanks by reporting the issue!!

**Comment by igorjrd** [comment]
@yak-22 
After a long period, I returned to work in the extension and performed some tests to evaluate a possible reason for the issue that you pointed. However, the extension seemed to provide adequate results when using styles with annotated bibliography. I tested with [APA 7th ed (annotated bibliography)](http://www.zotero.org/styles?q=id%3Aapa-annotated-bibliography) and the annotations were presented in the preview with no changes in the extension.

Is there a possibility that the reported issue occurred due to the CSL code that you were working at that time?
